### ISSUE TITLE
Bot support

### ISSUE THREAD

**Issue by JuniorJPDJ** [nktknshn/tgmount#1]
Hi,
I tried logging in as bot, when I found out that there's no way, I tried to put already logged in bot session to bot, but it failed:
```
$ ./tgmount.py --id -1001410674750 --list-documents                                                                                                                                                         
Traceback (most recent call last):
  File "./tgmount.py", line 209, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "./tgmount.py", line 70, in main
    await list_documents(await client(),
  File "/home/juniorjpdj/dev/tgmount/tgmount/tgmount/functions.py", line 50, in list_documents
    documents = await client.get_documents(entity,
  File "/home/juniorjpdj/dev/tgmount/tgmount/tgmount/tgclient.py", line 313, in get_documents
    [messages, documents] = await self._get_documents(entity,
  File "/home/juniorjpdj/dev/tgmount/tgmount/tgmount/tgclient.py", line 292, in _get_documents
    messages = await self.get_messages(entity, limit=limit, offset_id=offset_id, reverse=reverse,
  File "/usr/lib/python3.8/site-packages/telethon/client/messages.py", line 531, in get_messages
    return await it.collect()
  File "/usr/lib/python3.8/site-packages/telethon/requestiter.py", line 113, in collect
    async for message in self:
  File "/usr/lib/python3.8/site-packages/telethon/requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "/usr/lib/python3.8/site-packages/telethon/client/messages.py", line 165, in _load_next_chunk
    r = await self.client(self.request)
  File "/usr/lib/python3.8/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/lib/python3.8/site-packages/telethon/client/users.py", line 77, in _call
    result = await future
telethon.errors.rpcerrorlist.BotMethodInvalidError: The API access for bot users is restricted. The method you tried to invoke cannot be executed as a bot (caused by SearchRequest)
```

Also when I tried to mount:
```
./tgmount.py --id -1001410674750 --mount ./dir --debug --debug-fuse                                                                                                                                         46.175.44.195   93%  ─╯
DEBUG   [root]  Namespace(all_files=False, debug=True, debug_fuse=True, download=None, files=[], fsname='tgfs', id='-1001410674750', json=False, limit=None, list_dialogs=False, list_documents=False, mount='./dir', no_updates=False, offset_id=0, reverse=False, session='tgfs', socks=None)
DEBUG   [tgclient]      Connecting to Telegram servers...
INFO    [telethon.network.mtprotosender]        Connecting to 149.154.167.92:443/TcpFull...
INFO    [telethon.network.mtprotosender]        Connection to 149.154.167.92:443/TcpFull complete!
DEBUG   [tgclient]      Connected
DEBUG   [pyfuse3]       Calling fuse_session_unmount
[1]    143926 segmentation fault (core dumped)  ./tgmount.py --id -1001410674750 --mount ./dir --debug --debug-fuse
```

**Comment by mishailovic** [comment]
I'm having similar problem, did you solve it?

**Comment by JuniorJPDJ** [comment]
No and I'm not sure if it's possible to be solved.
Just use normal telegram account.

**Comment by divadsn** [comment]
This will never work, as Telegram restricts access to chat history for bot accounts.

https://core.telegram.org/method/messages.getHistory

**Comment by JuniorJPDJ** [comment]
Ok, It's not possible then. Closing!
