### ISSUE TITLE
TypeError: 'Message' object is not subscriptable

### ISSUE THREAD

**Issue by rajil** [nktknshn/tgmount#14]
```
$ python3 tgmount.py --download /tmp/files/ --id blahblah --files 17525,17526
INFO    [root]  Download files [17525, 17526] from blahblah to /tmp/files/
Traceback (most recent call last):
  File "tgmount.py", line 168, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "tgmount.py", line 81, in main
    await download(await client(),
  File "/home/media/tgmount/tgmount/tgmount/actions.py", line 156, in download
    ([d['attributes']['file_name'] for m, d in documents],))
  File "/home/media/tgmount/tgmount/tgmount/actions.py", line 156, in <listcomp>
    ([d['attributes']['file_name'] for m, d in documents],))
TypeError: 'Message' object is not subscriptable
```

**Comment by nktknshn** [comment]
Try new version of tgmount https://github.com/nktknshn/tgmount-ng
